POST http://localhost:3000/artists HTTP/1.1
content-type: application/json

  {
    "firstName": "Leonardo",
    "lastName": "Da Vinci",
    "overallGenre": "Renaissance",
    "showing": "True",
    "metrics": "5"
  }

###

POST http://localhost:3000/showtimes HTTP/1.1
content-type: application/json

 {
    "artist": "Pablo Picasso",
    "artistId": "63da55bc0f1733e8520a26d1",
    "currentlyShowing": false,
    "openingDate": "",
    "closingDate": ""
  }
  